server:
  port: 8083

# H2 database
#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update

# PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: postgres
    password: 1234
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect